// flow-typed signature: c782b723f9e0caec318d9b9c54af4e3e
// flow-typed version: <<STUB>>/vitest_v^0.34.6/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vitest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vitest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vitest/dist/browser' {
  declare module.exports: any;
}

declare module 'vitest/dist/child' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-api-setup.d65b007d' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-install-pkg.6c4f388a' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-integrations-globals.5afac659' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-node-git.36288174' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-runtime-console.ea222ffb' {
  declare module.exports: any;
}

declare module 'vitest/dist/cli-wrapper' {
  declare module.exports: any;
}

declare module 'vitest/dist/cli' {
  declare module.exports: any;
}

declare module 'vitest/dist/config' {
  declare module.exports: any;
}

declare module 'vitest/dist/coverage' {
  declare module.exports: any;
}

declare module 'vitest/dist/entry-vm' {
  declare module.exports: any;
}

declare module 'vitest/dist/entry' {
  declare module.exports: any;
}

declare module 'vitest/dist/environments' {
  declare module.exports: any;
}

declare module 'vitest/dist/execute' {
  declare module.exports: any;
}

declare module 'vitest/dist' {
  declare module.exports: any;
}

declare module 'vitest/dist/loader' {
  declare module.exports: any;
}

declare module 'vitest/dist/node' {
  declare module.exports: any;
}

declare module 'vitest/dist/reporters' {
  declare module.exports: any;
}

declare module 'vitest/dist/runners' {
  declare module.exports: any;
}

declare module 'vitest/dist/spy' {
  declare module.exports: any;
}

declare module 'vitest/dist/suite' {
  declare module.exports: any;
}

declare module 'vitest/dist/utils' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-_commonjsHelpers.7d1333e8' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-base.9c08bbd0' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-constants.538d9b49' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-coverage.78040316' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-date.6e993429' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-environments.7aba93d9' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-execute.07d1a420' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-global.97e4527c' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.0b5b3600' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.29282562' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.3e351f42' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.7646b3af' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.85fc950a' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.98139333' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.b271ebe4' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-inspector.47fc8cbb' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-node.a7c48fe1' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-paths.84fc7a99' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-reporters.f6975b8d' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-rpc.cbd8e972' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-run-once.3e5ef7d7' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-tasks.f9d75aed' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-vi.6873a1c1' {
  declare module.exports: any;
}

declare module 'vitest/dist/vm' {
  declare module.exports: any;
}

declare module 'vitest/dist/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vitest/dist/browser.js' {
  declare module.exports: $Exports<'vitest/dist/browser'>;
}
declare module 'vitest/dist/child.js' {
  declare module.exports: $Exports<'vitest/dist/child'>;
}
declare module 'vitest/dist/chunk-api-setup.d65b007d.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-api-setup.d65b007d'>;
}
declare module 'vitest/dist/chunk-install-pkg.6c4f388a.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-install-pkg.6c4f388a'>;
}
declare module 'vitest/dist/chunk-integrations-globals.5afac659.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-integrations-globals.5afac659'>;
}
declare module 'vitest/dist/chunk-node-git.36288174.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-node-git.36288174'>;
}
declare module 'vitest/dist/chunk-runtime-console.ea222ffb.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-runtime-console.ea222ffb'>;
}
declare module 'vitest/dist/cli-wrapper.js' {
  declare module.exports: $Exports<'vitest/dist/cli-wrapper'>;
}
declare module 'vitest/dist/cli.js' {
  declare module.exports: $Exports<'vitest/dist/cli'>;
}
declare module 'vitest/dist/config.js' {
  declare module.exports: $Exports<'vitest/dist/config'>;
}
declare module 'vitest/dist/coverage.js' {
  declare module.exports: $Exports<'vitest/dist/coverage'>;
}
declare module 'vitest/dist/entry-vm.js' {
  declare module.exports: $Exports<'vitest/dist/entry-vm'>;
}
declare module 'vitest/dist/entry.js' {
  declare module.exports: $Exports<'vitest/dist/entry'>;
}
declare module 'vitest/dist/environments.js' {
  declare module.exports: $Exports<'vitest/dist/environments'>;
}
declare module 'vitest/dist/execute.js' {
  declare module.exports: $Exports<'vitest/dist/execute'>;
}
declare module 'vitest/dist/index' {
  declare module.exports: $Exports<'vitest/dist'>;
}
declare module 'vitest/dist/index.js' {
  declare module.exports: $Exports<'vitest/dist'>;
}
declare module 'vitest/dist/loader.js' {
  declare module.exports: $Exports<'vitest/dist/loader'>;
}
declare module 'vitest/dist/node.js' {
  declare module.exports: $Exports<'vitest/dist/node'>;
}
declare module 'vitest/dist/reporters.js' {
  declare module.exports: $Exports<'vitest/dist/reporters'>;
}
declare module 'vitest/dist/runners.js' {
  declare module.exports: $Exports<'vitest/dist/runners'>;
}
declare module 'vitest/dist/spy.js' {
  declare module.exports: $Exports<'vitest/dist/spy'>;
}
declare module 'vitest/dist/suite.js' {
  declare module.exports: $Exports<'vitest/dist/suite'>;
}
declare module 'vitest/dist/utils.js' {
  declare module.exports: $Exports<'vitest/dist/utils'>;
}
declare module 'vitest/dist/vendor-_commonjsHelpers.7d1333e8.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-_commonjsHelpers.7d1333e8'>;
}
declare module 'vitest/dist/vendor-base.9c08bbd0.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-base.9c08bbd0'>;
}
declare module 'vitest/dist/vendor-constants.538d9b49.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-constants.538d9b49'>;
}
declare module 'vitest/dist/vendor-coverage.78040316.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-coverage.78040316'>;
}
declare module 'vitest/dist/vendor-date.6e993429.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-date.6e993429'>;
}
declare module 'vitest/dist/vendor-environments.7aba93d9.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-environments.7aba93d9'>;
}
declare module 'vitest/dist/vendor-execute.07d1a420.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-execute.07d1a420'>;
}
declare module 'vitest/dist/vendor-global.97e4527c.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-global.97e4527c'>;
}
declare module 'vitest/dist/vendor-index.0b5b3600.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.0b5b3600'>;
}
declare module 'vitest/dist/vendor-index.29282562.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.29282562'>;
}
declare module 'vitest/dist/vendor-index.3e351f42.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.3e351f42'>;
}
declare module 'vitest/dist/vendor-index.7646b3af.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.7646b3af'>;
}
declare module 'vitest/dist/vendor-index.85fc950a.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.85fc950a'>;
}
declare module 'vitest/dist/vendor-index.98139333.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.98139333'>;
}
declare module 'vitest/dist/vendor-index.b271ebe4.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.b271ebe4'>;
}
declare module 'vitest/dist/vendor-inspector.47fc8cbb.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-inspector.47fc8cbb'>;
}
declare module 'vitest/dist/vendor-node.a7c48fe1.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-node.a7c48fe1'>;
}
declare module 'vitest/dist/vendor-paths.84fc7a99.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-paths.84fc7a99'>;
}
declare module 'vitest/dist/vendor-reporters.f6975b8d.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-reporters.f6975b8d'>;
}
declare module 'vitest/dist/vendor-rpc.cbd8e972.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-rpc.cbd8e972'>;
}
declare module 'vitest/dist/vendor-run-once.3e5ef7d7.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-run-once.3e5ef7d7'>;
}
declare module 'vitest/dist/vendor-tasks.f9d75aed.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-tasks.f9d75aed'>;
}
declare module 'vitest/dist/vendor-vi.6873a1c1.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-vi.6873a1c1'>;
}
declare module 'vitest/dist/vm.js' {
  declare module.exports: $Exports<'vitest/dist/vm'>;
}
declare module 'vitest/dist/worker.js' {
  declare module.exports: $Exports<'vitest/dist/worker'>;
}
