// flow-typed signature: c1582f4a5fd85814ac0820269f611942
// flow-typed version: <<STUB>>/@krakenjs/cross-domain-safe-weakmap_v^2.0.2/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/cross-domain-safe-weakmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/cross-domain-safe-weakmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@krakenjs/cross-domain-safe-weakmap/dist/cross-domain-safe-weakmap' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-safe-weakmap/dist/cross-domain-safe-weakmap.min' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-safe-weakmap/dist/module' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-safe-weakmap/dist/module/native' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-safe-weakmap/dist/module/util' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-safe-weakmap/dist/module/weakmap' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-safe-weakmap/src' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-safe-weakmap/src/native' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-safe-weakmap/src/util' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-safe-weakmap/src/weakmap' {
  declare module.exports: any;
}

// Filename aliases
declare module '@krakenjs/cross-domain-safe-weakmap/dist/cross-domain-safe-weakmap.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/dist/cross-domain-safe-weakmap'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/dist/cross-domain-safe-weakmap.min.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/dist/cross-domain-safe-weakmap.min'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/dist/module/index' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/dist/module'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/dist/module/index.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/dist/module'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/dist/module/native.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/dist/module/native'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/dist/module/util.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/dist/module/util'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/dist/module/weakmap.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/dist/module/weakmap'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/src/index' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/src'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/src/index.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/src'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/src/native.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/src/native'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/src/util.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/src/util'>;
}
declare module '@krakenjs/cross-domain-safe-weakmap/src/weakmap.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-safe-weakmap/src/weakmap'>;
}
